# Generated by Django 4.2.2 on 2024-07-09 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="mane",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="codezipe",
            new_name="zipcode",
        ),
    ]
