# Generated by Django 4.2.2 on 2024-07-12 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_rename_mane_customer_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderPlace",
            new_name="OrderPlaced",
        ),
    ]
