# Generated by Django 4.2.2 on 2024-07-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_orderplace_orderplaced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Packet", "Packet"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                ],
                default=" Non Commencé",
                max_length=50,
            ),
        ),
    ]
